//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İlaçEczaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sube
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sube()
        {
            this.Calisan = new HashSet<Calisan>();
        }
    
        public int idSUBE { get; set; }
        public string Ad { get; set; }
        public string Adres { get; set; }
        public int CalisanKisiSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calisan> Calisan { get; set; }
    }
}
