//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İlaçEczaOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int kno { get; set; }
        public string kad { get; set; }
        public string ksifre { get; set; }
        public bool kyetki { get; set; }
    }
}
